In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/tshirts.csv")

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [7]:
df.shape

(39, 24)

In [27]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'price_after_tax'],
      dtype='str')

In [28]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price               float64
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
price_after_tax           float64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              39 non-null     int64
 1   title                   39 non-null     str
 2   product_description     39 non-null     str
 3   rating                  39 non-null     float64
 4   ratings_count           39 non-null     int64
 5   initial_price           39 non-null     float64
 6   discount                32 non-null     float64
 7   final_price             39 non-null     str
 8   currency                39 non-null     str
 9   images                  39 non-null     str
 10  delivery_options        39 non-null     str
 11  product_details         39 non-null     str
 12  breadcrumbs             39 non-null     str
 13  product_specifications  39 non-null     str
 14  amount_of_stars         39 non-null     str
 15  what_customers_said     30 non-null     str
 16  seller_name             18 non-null     str
 17  sizes                   39 non-null     str
 18  videos                  10 non-null     str
 19  seller_information      18 non-null     str
 20  variations              14 non-null     str
 21  best_offer              39 non-null     str
 22  more_offers             39 non-null     str
 23  category                39 non-null     str
dtypes: float64(3), int64(2), str(19)
memory usage: 7.4 KB

In [10]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [14]:
df = df.fillna("Unknown")

In [16]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.drop_duplicates(inplace=True)

In [22]:
df[['title', 'final_price', 'rating']]

                        title  final_price  rating
0                       ether  "₹1,099.00"     4.4
1              Mast & Harbour    "₹899.00"     4.2
2              Mast & Harbour    "₹999.00"     3.9
3                 Urbano Plus  "₹1,099.00"     3.2
4                     ScoldMe    "₹719.00"     0.0
5                UNDER ARMOUR  "₹1,999.00"     4.3
6                    Roadster    "₹899.00"     3.8
7              Tommy Hilfiger  "₹2,799.00"     4.4
8                       WROGN  "₹1,599.00"     4.2
9                    Roadster    "₹999.00"     4.2
10             Tommy Hilfiger  "₹1,999.00"     4.4
11                   Roadster    "₹799.00"     4.1
12                       Puma  "₹3,999.00"     4.4
13                      Camey    "₹999.00"     3.5
14                      Kappa    "₹599.00"     3.2
15            U.S. Polo Assn.  "₹1,699.00"     4.5
16                   Roadster  "₹1,399.00"     4.0
17                       Puma  "₹1,499.00"     4.3
18                   Roadster  "₹1,399.00"     4.1
19          Allen Solly Tribe  "₹1,499.00"     4.3
20             Arrow New York    "₹674.00"     4.8
21                Aeropostale  "₹1,199.00"     4.2
22                   Roadster    "₹404.00"     4.4
23               Miss & Chief    "₹578.00"     3.9
24                   Friskers  "₹1,229.00"     0.0
25                       Parx    "₹699.00"     4.9
26                   Bewakoof    "₹549.00"     4.2
27              Tokyo Talkies    "₹293.00"     4.1
28                Monte Carlo    "₹835.00"     4.8
29                    CHKOKKO    "₹499.00"     3.7
30                    BULLMER    "₹799.00"     4.8
31                     Braveo    "₹384.00"     0.0
32  AMERICAN EAGLE OUTFITTERS    "₹359.00"     4.4
33                Allen Solly    "₹599.00"     4.4
34                        max    "₹479.00"     4.4
35             Mad Over Print    "₹671.00"     4.8
36                   FERANOID    "₹599.00"     4.2
37             Flying Machine    "₹389.00"     4.0
38             Flying Machine    "₹506.00"     3.8

In [24]:
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

In [25]:
filtered_df = df[df['final_price'] > 500]

filtered_df[['title', 'final_price']].head()

Empty DataFrame
Columns: [title, final_price]
Index: []

In [26]:
df['price_after_tax'] = df['final_price'] * 1.18

In [29]:
df.to_csv("../output/cleaned_tshirts.csv", index=False)